### ISSUE TITLE
Throttling for "Rate Limit Exceeded" - 509 and 429's

### ISSUE THREAD

**Issue by jtallieu** [bigcommerce/bigcommerce-api-python#12]
I built in sleep "delay" and "max_retries" into my original version of the API to address the 509 errors.  I do not want to have to wrap every operation throughout my application to address the retries.  I'd prefer it be built into the API so that it is transparent.  It could also be configurable when instantiating the API class.

The 429's are nice in that it gives you a "retry-after" in the header.

What are your thoughts on this?  Is there a good reason that this should not be part of the API?

Thank you.

**Comment by gabelimon** [comment]
Putting this on my todo list. I've also had the PM for our API look at your feature request for 429's.

**Comment by bookernath** [comment]
Fixed/improved in https://github.com/bigcommerce/bigcommerce-api-python/pull/75
