### ISSUE TITLE
even after successfully running server, my app in My Drafts is not installing to my store

### ISSUE THREAD

**Issue by svcew-dinesh** [bigcommerce/bigcommerce-api-python#14]
the process i executed is 1) cloned git repository into my PC , 2) created an app in https://developer.bigcommerce.com/ , 3) copied the app key and app secret in config.py, 4)  ran the app.py and then while installing my app it asked for confirmation and when i clicked it there is no response except just showing installing...

**Comment by gabelimon** [comment]
Hi @svcew-dinesh, did you ever work through this issue? It sounds like there may be an issue in either developer documentation or in the sample app so I'd love to get more details.

**Comment by bookernath** [comment]
Is this still an issue? I've just updated the hello world app to have a really streamlined deploy process to Heroku, might give that a shot - https://github.com/bigcommerce/hello-world-app-python-flask
