### ISSUE TITLE
Helper method for creating an authorize URL

### ISSUE THREAD

**Issue by dasevilla** [bigcommerce/bigcommerce-api-python#19]
Would be nice to have a method that generates the authorize URL

Also, the developer site doesn't document what the authorize URL is. I had to guess what it is:

```
https://login.bigcommerce.com/oauth2/authorize
```

**Comment by gabelimon** [comment]
I believe you're looking for [this method](https://github.com/bigcommerce/bigcommerce-api-python/blob/master/bigcommerce/connection.py#L216). I'm going to close this but feel free to open tickets if this doesn't quite do what you need.

**Comment by dasevilla** [comment]
That method (request to the token endpoint) is the last step in the OAuth 2.0 Authorization Code grant. I'm asking about the first step: generating a URL to send the user's browser to so they can approve access.

**Comment by gabelimon** [comment]
Yeah you're right. Sorry for dropping the ball on that one. I'll find what you need or add it. I'm guessing it's somewhere in the sample flask app.

**Comment by bookernath** [comment]
Recommend using the code from the [sample app](https://github.com/bigcommerce/hello-world-app-python-flask) for this.
