### ISSUE TITLE
Release `0.13.0` not uploaded to PyPi

### ISSUE THREAD

**Issue by hockeybuggy** [bigcommerce/bigcommerce-api-python#35]
Not super pressing but a tag for version`0.13.0` ~~`0.12.0`~~ was created on github but [wasn't published to the cheese shop](https://pypi.python.org/pypi/bigcommerce).

**Comment by hockeybuggy** [comment]
@PascalZajac @bookernath Do you have you have the ability to update the package or Pypi?

**Comment by bookernath** [comment]
@hockeybuggy I just recently got access. I'll take a look.

**Comment by bookernath** [comment]
@hockeybuggy all set!

**Comment by hockeybuggy** [comment]
Thanks @bookernath! Looks great.
