### ISSUE TITLE
Library is not documented on Bigcommerce Developer Portal

### ISSUE THREAD

**Issue by sabotagebeats** [bigcommerce/bigcommerce-api-python#58]
### Expected behavior
should be documented at https://developer.bigcommerce.com/ as per https://github.com/bigcommerce/bigcommerce-api-python#further-documentation

### Actual behavior
no documentation 

### Steps to reproduce behavior
go to https://developer.bigcommerce.com/ there is no documentation for this library.

**Comment by PreciselyAlyss** [comment]
@sabotagebeats Do you mean that the client library isn't listed on the api documentation? 

We currently have [this client library section](https://developer.bigcommerce.com/api/#client-libraries). Are you expecting something other than this?

**Comment by bookernath** [comment]
@sabotagebeats the developer portal provides further documentation on the actual APIs, not the API client itself. As an example, you can see information about the V2 Products API here: https://developer.bigcommerce.com/api/v2/#products

**Comment by sabotagebeats** [comment]
I guess I misunderstood I was under the impression there would be
documentation for this library located there.  I understand now I can use
v2 api documentation.
Thank you.

**Comment by bookernath** [comment]
No problem! Let me know if you have other queries.
