### ISSUE TITLE
Cannot generate a valid jwt-login-token... Something to do with APP_CLIENT_SECRET?

### ISSUE THREAD

**Issue by ohabash** [bigcommerce/bigcommerce-api-python#61]
I am new to bigCommerce so bare with me please. Any help is appreciated.

### Expected behavior
I am working with `ex_login_token.py`... I expect the JWT token to be able to log me in. ((SSO))

### Actual behavior
when i go to use the token `https://myURL.com/login/token/<jwt-login-token>`  i get redirected instead to the login page of my bc store with the error `Invalid login..`

I have a working flask app installed in my bigcommerce store. I might need to merge that app and the python script somehow so that the `APP_CLIENT_SECRET` is works. but i have little knowledge in a lot of places. I need help filling a few gaps

**Comment by bookernath** [comment]
Hi,

In general, you'll need to make sure that your application supports environment variables, and make sure that your app's client secret (from your app's listing on https://devtools.bigcommerce.com) is set as that environment variable. This shared secret that only your app and BC are aware of will be used to sign the JWT URL, securing it against just anyone generating login tokens.
