### ISSUE TITLE
force_reset not working

### ISSUE THREAD

**Issue by ohabash** [bigcommerce/bigcommerce-api-python#62]
### Expected behavior
I need to create a customer and force them to reset their passwords on login. I tried the following...
`api.Customers.create(first_name=first, last_name=last, email=email, force_reset=True)`
-or-
`api.Customers.create(first_name=first, last_name=last, email=email, _authentication:{force_reset=True})`

### Actual behavior
`ClientRequestException: 400 Bad Request @ customers: [{"status":400,"message":"The field 'force_reset' is not supported by this resource."}]`

How can i use the api to set `reset_pass_on_login` to true?

**Comment by bookernath** [comment]
Hi,

You need to pass force_reset as an object, like this:

`forceResetObject = dict(force_reset=True)
api.Customers.get(custId).update(_authentication=forceResetObject)`
