### ISSUE TITLE
406 Not Acceptable ({"error":"Invalid format."}) during api.oauth_fetch_token call

### ISSUE THREAD

**Issue by Hitoki** [bigcommerce/bigcommerce-api-python#66]
### Expected behavior
api = bigcommerce.api.BigcommerceApi(
    client_id=config['bigcommerce'].get('client_id'),
    store_hash=context, access_token='')

token = api.oauth_fetch_token(
    config['bigcommerce'].get('client_secret'), code, context, scope,
    config['bigcommerce'].get('redirect_uri'))
print(token)
>>> {'access_token': '***', 'scope': '***', 'user':***, 'context': '***'}
### Actual behavior
Python 3.6.3 
bigcommerce==0.18.0

api = bigcommerce.api.BigcommerceApi(
    client_id=config['bigcommerce'].get('client_id'),
    store_hash=context, access_token='')

token = api.oauth_fetch_token(
    config['bigcommerce'].get('client_secret'), code, context, scope,
    config['bigcommerce'].get('redirect_uri'))

>>> bigcommerce.exception.ClientRequestException: 406 Not Acceptable @ https://login.bigcommerce.com/oauth2/token: b'{"error":"Invalid format."}'

### Steps to reproduce behavior
Upgrade bigcommerce to 0.18.0 (from the bigcommerce==0.17.3)

pip install bigcommerce==0.18.0
running in powershell terminal

**Comment by bookernath** [comment]
@surbas any thoughts on this? I think this might have been introduced as a result of your work.

**Comment by surbas** [comment]
Happy to take a look in a bit. Just wondering what leads you to think it
something with the iterall?. This looks like this has to do with
authentication.

**Comment by bookernath** [comment]
Just because of the changeset between the two versions - 0.17.3 works fine, and 0.18.0 is broken. Majority of the commits between the two are yours :)

**Comment by surbas** [comment]
@bookernath I took a look at the blame for the `oauth_fetch_token` and `fetch_token` methods that are throwing the `ClientRequestException`. The code for either has not change in 3 to 4 years and hence has nothing to do with the `iteradd` work that I donated. Since I was already here... I took a deeper dive It seems like this is your server throwing an error.  My gut tells me from looking at these functions that fault lies either on the input or the server. The code in question is doing a simple POST with very little handling of the inputs as far as I can tell.

**Comment by bookernath** [comment]
@surbas I narrowed the issue down to the changes to connection.py in this commit: https://github.com/bigcommerce/bigcommerce-api-python/commit/a9d9ba016521d5c1b061c4c07bd6c28e55c3b333

I think it's related to some of the refactoring; the OAuth token POST request uses the same methods as other API requests, and a lot of the underpinnings of that (fetch_token --> post --> run_method) are touched by your changes here.

Still digging into it...

**Comment by surbas** [comment]
@bookernath What are the steps to reproduce the reported bug to narrow down issue? Happy to write test and fix.

**Comment by bookernath** [comment]
@surbas thanks for the follow-up!

- Install 0.18.0 or install the exact commit I mentioned
- Create a draft app (you can use https://github.com/bigcommerce/hello-world-app-python-flask on heroku easily)
- Try to install the app, get a 406 error as above
- If you switch your version to 0.18.1 or 0.17.3 this does not happen

**Comment by surbas** [comment]
@bookernath i just tried to deploy to heroku and got the following error: This is using the button on your link.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/app.py", line 4, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'

**Comment by bookernath** [comment]
@surbas I've updated the requirements.txt and it works now. Nice catch!

**Comment by surbas** [comment]
@bookernath switched to local. I can hit /instructions.html. When you say "install the app" you talking about heroku (which i was assuming) or on big commerce?

**Comment by bookernath** [comment]
@surbas I mean to attempt the [app installation flow](https://developer.bigcommerce.com/api/#app-installation-and-update-sequence) by installing the draft app in your BC control panel.

To do this, you'll need to follow the [full set of instructions](https://github.com/bigcommerce/hello-world-app-python-flask#getting-started-heroku-version) and have a draft app [created in BC](https://devtools.bigcommerce.com/). The error only occurs when the app is being installed, which is when the OAuth token exchange happens.
